### ISSUE TITLE
Visualizing `value` for server timing entries

### ISSUE THREAD

**Issue by cvazac** [w3c/server-timing#22]
At present, Chrome devtools infers time in milliseconds from the numeric value of server timing header entries:
1) the column header is "TIME"
2) the numeric value is given a unit of "ms" 
3) the horiz bar fills as a percentage of total request time

![image](https://user-images.githubusercontent.com/9857665/28439734-ceb839ee-6d68-11e7-9ae9-c500c18f4fec.png)

As per spec, this number is just a double: it can be an ID, byte count, shard count, a time measurement in seconds, etc. Along with the fact that there is no `startTime` on these entries, it makes visualization a tricky subject. 

from @paulirish

> I'd like DevTools to continue visualizing these values with a millisecond-based time scale that's based on the request's total time. This means we may show a weird visual if the value is for byte counts, shard counts, etc, but I think this is worth it, as the alternative is we give up on the visual and just show a basic table.

cc @igrigorik

**Comment by igrigorik** [comment]
Well, to start, it's worth noting that we are discussing this in context of Server _Timing_... :-)

Taking a step back, a few observations:

Given that the values are provided by the user/server, we cannot "force" the user to provide timestamps. As such, nothing stops them from passing shard counts, ..., whatever they want. On the other hand, the reason DevTools is able to give developers pretty graphs is precisely because it assumes the user is conforming to the spec and passing in time values.

We could relax the definition of "value" to a double, but then I think we would have to give up on the pretty visualizations and instead assume a mixed bag of types -- this makes it tricky to interpret the data for upstream tools, like DevTools and RUM providers; the best they could do is display such data as a table, or some such. Also, if we go down that route, we should reconsider the name.. since it's no longer "timing" only.

Alternatively, we keep the value definition as DomHighResTimestamp (https://github.com/w3c/server-timing/pull/23). This doesn't stop developers from passing in other numeric types, but if they do, that's their own decision. Also, we do allow arbitrary payloads via "description" (DOMString), which could be used for non-time data and already needs to be displayed as a table -- in effect, you could have the best of both worlds.. Pass in time based data via value and other types via description.

---

FWIW, I'm happy to be convinced either way.. I just want to make sure we all understand the tradeoffs. Personally, I think relaxing type requirement for value actually makes things less appealing, since upstream tools can't do as good of a job with visualizing durations. Also, I don't think we want to go down the route of also communicating per-field types, etc, in HTTP headers.

**Comment by cvazac** [comment]
For the sake of upstream tools, I agree that this field should be _encouraged_ to be time as millis.

Going further, should we rename it back to `duration`? I could be convinced, but at present I think it should stay `value` to distinguish from user agent-generated `duration` values on `PerformanceEntry` objects.

**Comment by igrigorik** [comment]
But we are asking developers to communicate durations, right? :-) Not timestamps that can't be mapped into a timeline.. So, wouldn't calling the field `duration` offer a strong positive nudge to not get it wrong?

**Comment by cvazac** [comment]
Yes, it is a solid nudge. :)

But, as we use `metric` to store the user-defined name of the server timing entry to avoid confusion with the `name` attribute on `PerformanceEntry`, it might make sense to use `value` as the user-defined numeric, versus the browser controlled `duration` on `PerformanceEntry`.

**Comment by igrigorik** [comment]
True, but same argument in opposite direction, why not `name` and `duration`? The fact that it's user provided is -- to me -- less important than consistency and predictability of the API. Case in point, you can pass in arbitrary values into User Timing measures.. WDYT?

**Comment by cvazac** [comment]
I think we have our winner. :)
https://github.com/w3c/server-timing/pull/25

**Comment by igrigorik** [comment]
👍

**Comment by igrigorik** [comment]
Closing, resolved via #25.
